version: '3.8'

services:
  face-app:
    build:
      context: .
      dockerfile: Dockerfile.faceapp-preprocess
    volumes:
      - ./data/celebA:/app/data/celebA
      - ./data/output:/app/data/output
      - ./data/samples:/app/data/samples
      - ./data/preprocessed:/app/data/preprocessed
      - ./face-app/models:/root/.insightface/models  # Volume pour persister le modèle téléchargé dans face-app/models
    ports:
      - "6000:6000"
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: ${DOCKER_RUNTIME:-runc}  # Utilise 'nvidia' si DOCKER_RUNTIME est défini, sinon 'runc' pour CPU
