FROM node:18-alpine
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run 
FROM nginx:alpine
COPY --from=0 /app /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]