version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3030:80"
    restart: always
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5050:5000"
    volumes:
      - ./backend:/app
      - ./data:/app/data