services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3030:80"
    restart: "always"
<<<<<<< HEAD
=======

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5050:5000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
>>>>>>> AI-test

  face-app:
    build:
      context: .
      dockerfile: Dockerfile.faceapp-app
    volumes:
      - ./data/celebA:/app/data/celebA
      - ./data/output:/app/data/output
      - ./data/samples:/app/data/samples
      - ./data/preprocessed:/app/data/preprocessed
      - ./face-app/models:/root/.insightface/models  # Volume pour persister le modèle téléchargé dans face-app/models
    ports:
      - "5050:5050"
    restart: "no"
<<<<<<< HEAD
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
=======
>>>>>>> AI-test
